import { z } from "zod";

const EnvSchema = z.object({
  SUPABASE_URL: z.string().url(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().min(1),
  FLOORPLAN_UPLOAD_BUCKET: z.string().default("floor-plans"),
  ASSET_STORAGE_BUCKET: z.string().default("assets-glb"),
  WORKER_CONCURRENCY: z.coerce.number().default(2),
  WORKER_POLL_INTERVAL_MS: z.coerce.number().default(1000),
  ASSET_GENERATION_POLL_INTERVAL_MS: z.coerce.number().default(2000),
  ASSET_GENERATION_MAX_POLLS: z.coerce.number().default(45),
  FLOORPLAN_PROVIDER_ORDER: z.string().default("anthropic,openai,snaptrude"),
  FLOORPLAN_PREPROCESS_PROFILES: z.string().default("balanced,lineart,filled_plan"),
  FLOORPLAN_PROVIDER_TIMEOUT_MS: z.coerce.number().default(45000),
  FLOORPLAN_MIN_ACCEPT_SCORE: z.coerce.number().default(25),
  FLOORPLAN_REVIEW_SCORE_THRESHOLD: z.coerce.number().default(72),
  FLOORPLAN_REVIEW_CONFLICT_THRESHOLD: z.coerce.number().default(0.3),
  FLOORPLAN_REVIEW_DIMENSION_CONFLICT_THRESHOLD: z.coerce.number().default(0.35),
  FLOORPLAN_REVIEW_SCALE_CONFLICT_THRESHOLD: z.coerce.number().default(0.35),
  ANTHROPIC_API_KEY: z.string().min(1).optional(),
  OPENAI_API_KEY: z.string().min(1).optional(),
  SNAPTRUDE_API_URL: z.string().url().optional(),
  SNAPTRUDE_API_KEY: z.string().min(1).optional(),
  ROBOFLOW_CUBICASA2_URL: z.string().url().optional(),
  ROBOFLOW_CUBICASA3_URL: z.string().url().optional(),
  ROBOFLOW_API_KEY: z.string().min(1).optional(),
  PADDLEOCR_API_URL: z.string().url().optional(),
  PADDLEOCR_API_TOKEN: z.string().min(1).optional(),
  PADDLEOCR_DET_MODEL: z.string().optional(),
  PADDLEOCR_REC_MODEL: z.string().optional(),
  HF_FLOORPLAN_ENDPOINT_URL: z.string().url().optional(),
  HF_FLOORPLAN_ENDPOINT_TOKEN: z.string().min(1).optional(),
  TRIPOSR_API_URL: z.string().url().optional(),
  TRIPOSR_API_KEY: z.string().min(1).optional(),
  TRIPOSR_STATUS_URL: z.string().url().optional(),
  MESHY_API_URL: z.string().url().optional(),
  MESHY_API_KEY: z.string().min(1).optional(),
  MESHY_STATUS_URL: z.string().url().optional()
});

export const env = EnvSchema.parse(process.env);
